agnez_core_anno:
    resource: "@AgnezCoreBundle/Controller/DefaultController.php"
    type:     annotation

agnez_core:
    resource: "@AgnezCoreBundle/Resources/config/routing.yml"
    prefix:   /

agnez_user:
    resource: "@AgnezUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
