services:
    agnez_core.servicedate:
        class : Agnez\CoreBundle\ServiceDate\AgnezServiceDate
        arguments :  ['2017-09-04']

    agnez_core.initEdt:
        class : Agnez\CoreBundle\ServiceDate\AgnezInitEdt
