services:
    agnez_core.servicedate:
        class : Agnez\CoreBundle\ServiceDate\AgnezServiceDate
        arguments :  ['2017-09-04']

    agnez_core.serviceinitEdt:
        class : Agnez\CoreBundle\ServiceInitEdt\AgnezServiceInitEdt
        arguments :  ['@agnez_core.servicedate',40]

    agnez_core.servicegetSem:
        class : Agnez\CoreBundle\ServiceGetSem\AgnezServiceGetSem
