<?php

namespace Agnez\CoreBundle\Repository;

/**
 * EdtHeureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdtHeureRepository extends \Doctrine\ORM\EntityRepository
{
}
